[IMP] server_environment: allow env variable conf
OCA/server-env pull request #189
Opened 2024-06-24 14:44 UTC by denaux

I would like to propose a forward port of [one specific commit from v14](https://github.com/OCA/server-env/commit/4286429cba03173804ff5855eeb5f282227bbff2). This opens up compatibility with Odoo.sh.

2024-06-25 06:26 UTC, gurneyalex approved these changes

2024-06-27 07:09 UTC, simahawk requested changes
@denaux thanks for your contrib.
Question: how have you ported the commit? Seems the original authorship is lost.
You should use  cherry pick to preserve it. Could you check please?

2024-06-27 08:20 UTC, denaux commented
@simahawk Thanks for the heads-up. This should be fixed now.

2024-07-11 04:28 UTC, nilshamerlinck approved these changes

2024-07-11 07:33 UTC, simahawk approved these changes

2024-07-11 07:34 UTC, simahawk commented
/ocabot merge minor

Thanks! Would you mind opening a PR for 14 and 15?

2024-07-11 07:38 UTC, merged