pre-commit, black, isort
OCA/server-env pull request #33
Opened 2019-10-12 10:58 UTC by sbidoul

This one requires a manual intervention to fix a pylint error (missing super).

2019-10-12 11:01 UTC, sbidoul commented
@grindtildeath, I'm assigning to you as you made the migration.

2019-10-22 16:04 UTC, grindtildeath commented
@sbidoul Sorry I missed your ping, here's the fix https://github.com/acsone/server-env/pull/1

2019-10-22 16:32 UTC, sbidoul commented
@grindtildeath the lint phase is red now. Can you re-do your commit with a 'pre-commit run --all-files'?

2019-10-23 08:29 UTC, grindtildeath commented
@sbidoul My bad, fixed now.

2019-11-12 12:53 UTC, sbidoul commented
/ocabot merge patch

2019-12-16 10:49 UTC, yvaucher requested changes

2019-12-16 10:49 UTC, yvaucher commented on .travis.yml
> -  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
The addition of `running_env` is necessary for `server_environment` module.

2019-12-16 10:49 UTC, yvaucher commented on .travis.yml
>    - travis_install_nightly
```suggestion
  - travis_install_nightly
  # Requirements to test server_environment modules
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
```

2019-12-16 10:51 UTC, yvaucher commented on .travis.yml
>    - travis_install_nightly
I have to check if now it's odoo_serverrc instead.

2019-12-16 10:54 UTC, yvaucher commented on .travis.yml
>    - travis_install_nightly
I confirm it didn't change https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server.py#L270

2019-12-16 10:58 UTC, yvaucher commented on .travis.yml
> -  - ln -s ${TRAVIS_BUILD_DIR}/server_environment_files_sample ${TRAVIS_BUILD_DIR}/server_environment_files
This on the other hand might not be necessary anymore.

2019-12-16 11:40 UTC, sbidoul commented
Feel free to take over this PR, I've no time to work on it short term.

2019-12-16 12:09 UTC, yvaucher commented
@sbidoul Ok, will do

2019-12-16 12:14 UTC, yvaucher commented
superseeded by https://github.com/OCA/server-env/pull/36

2019-12-16 12:14 UTC, closed without merging