14.0 mig server environment
OCA/server-env pull request #62
Opened 2020-10-12 08:47 UTC by mourad-ehm

2020-10-12 16:18 UTC, bealdav requested changes
Thanks for your contribution. Some typo remarks only

2020-10-12 16:18 UTC, bealdav commented on server_environment/readme/CONFIGURE.rst
> +Keychain integration
It seems keychain no more exists replaced by ...

2020-10-12 16:18 UTC, bealdav commented on server_environment/server_env.py
> +#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
probably could be made shorter

2020-10-12 16:18 UTC, bealdav commented on server_environment/system_info.py
> +#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
probably could be made shorter header

2020-10-12 16:18 UTC, bealdav commented on server_environment/server_env.py
> +        ModelClass = super(ServerConfiguration, cls)._build_model(pool, cr)
```suggestion
        ModelClass = super()._build_model(pool, cr)
```

2020-10-15 10:09 UTC, bealdav approved these changes

2020-10-16 07:38 UTC, sbejaoui approved these changes
LGTM, thank you

2020-10-16 09:42 UTC, sebastienbeau commented
/ocabot merge nobump

2020-10-16 09:57 UTC, merged