WIP [14.0][ADD] auth_saml_enviroment
OCA/server-env pull request #74
Opened 2021-06-15 13:23 UTC by leemannd

2021-06-16 13:35 UTC, yvaucher approved these changes
LGTM

just a print to remove and doc to fill

2021-06-16 13:36 UTC, yvaucher commented on server_environment/models/server_env_mixin.py
> +            print(field_name, config_getter)
:eyes:

2021-06-16 13:39 UTC, leemannd commented on server_environment/models/server_env_mixin.py
> +            print(field_name, config_getter)
Todo remove it

2021-06-25 09:38 UTC, theangryangel requested changes

2021-06-25 09:38 UTC, theangryangel commented on auth_saml_environment/controllers/main.py
> +        return []
Upstream auth_saml basically does the same thing now, so I think this isn't needed any more? Beyond that it works great in our test environment :)

2021-09-21 12:07 UTC, leemannd commented
The linked module has been merged. Could we consider merging it? cc @yvaucher

2021-09-27 10:53 UTC, simahawk commented
@leemannd build is red. Also, pls squash commit when done

2021-09-27 10:59 UTC, SilvioC2C approved these changes
LGTM

2021-09-27 12:24 UTC, yvaucher commented on auth_saml_environment/tests/test_environment_variable.py
> +                dict(parser["sample"].items()),
Unit test gives a `KeyError: 'sample'` on this line.

Shouldn't it be `auth_saml_provider.sample` ?

2021-10-26 08:52 UTC, leemannd commented on auth_saml_environment/tests/test_environment_variable.py
> +                dict(parser["sample"].items()),
Fixed. Thanks

2021-10-26 14:53 UTC, leemannd commented
@simahawk @yvaucher Tests fixed. Can be merged

2021-10-26 15:11 UTC, simahawk commented
/ocabot merge nobump

2021-10-26 15:24 UTC, merged