[14.0][FW] server_environment_ir_config_parameter: Port PR from 12.0/13.0 to 14.0
OCA/server-env pull request #92
Opened 2021-11-29 08:57 UTC by sonhd91

This PR migrate [PR#67](https://github.com/OCA/server-env/pull/67) from 12.0 to 14.0

2021-11-29 11:03 UTC, simahawk approved these changes

2021-11-29 11:03 UTC, simahawk commented on server_environment_ir_config_parameter/__manifest__.py
> +    'demo': [
demo is not required

2021-11-29 11:49 UTC, simahawk commented
pre-commit is not happy

2021-11-29 11:50 UTC, simahawk requested changes
small things to fix

2021-12-02 06:25 UTC, sonhd91 commented
> pre-commit is not happy

Thanks, branch updated

2021-12-02 06:54 UTC, simahawk approved these changes

2021-12-02 11:48 UTC, yvaucher approved these changes

2021-12-02 12:39 UTC, simahawk commented
/ocabot merge minor

2021-12-02 12:49 UTC, merged